services:
  # Backend API Service
  - type: web
    name: edtech-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here:
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: edtech-db
    #     property: connectionString
    # - key: JWT_SECRET
    #   generateValue: true

  # Frontend Web Service
  - type: web
    name: edtech-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://edtech-backend.onrender.com/graphql

# Uncomment and configure if you need a database
# databases:
#   - name: edtech-db
#     plan: free